### ISSUE TITLE
Does not respect the -n (--dry-run) flag

### ISSUE THREAD

**Issue by edslocomb** [mydrive/capistrano-deploytags#26]
Title says it all; tags are pushed even when --dry-run is specified on the command line.

**Comment by gavinheavyside** [comment]
Hi Ed, 

I've just tried running with --dry-run here, and the deploytags tasks aren't invoked, and no tags are pushed.

Please could you tell us more about your setup? Ruby version, Capistrano version, capistrano-deploytags version, and if possible your config/deploy.rb?

**Comment by edslocomb** [comment]
Ruby 2.2.2, Capistrano 3.4.0, rake 10.4.2, capistrano-deploytags 1.0.2, git version 2.4.0, OSX 10.10.3

Capfile contains: 

    require 'capistrano/deploytags'

deploy.rb contains nothing relating to deploytags.  origin is on github; a page reload is needed to see the tags, but they're definitely gettting pushed on --dry-run
