### ISSUE TITLE
Release version with fix for deploytag_commit_message variable

### ISSUE THREAD

**Issue by wildtangent** [mydrive/capistrano-deploytags#32]
Currently 1.0.4 contains an issue if you try and set the `deploytag_commit_message` variable since it is  not using the `fetch(:deploytag_commit_message)` method in the helper. Please can you push a version to RubyGems with this applied?

thanks!

**Comment by gavinheavyside** [comment]
I've pushed version 1.0.6, based on current master HEAD - https://rubygems.org/gems/capistrano-deploytags/versions/1.0.6
